title: Gothic Archive Wiki
description: Gothic Archive | Wiki
author: PhoenixTales
theme: null
layouts_dir: ./_templates
includes_dir: ./_templates
paginate: 4
paginate_path: "/:num"
permalink: /:year/:month/:day/:title
exclude: [ vendor ]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
collections:
  category:
    output: true
plugins:
  - github-pages
  - jekyll-paginate
